### ISSUE TITLE
Separate uploading and parsing of an archive

### ISSUE THREAD

**Issue by nodestory** [bitmark-inc/datapod#5]
## Rationale
1. If the parsing fails, the archive doesn't have to be uploaded again.
2. Each archive is attached with a unique ID so it can be used to distinguish parsed data from multiple archives.

### Upload an archive

Duplicate uploads will be ignored.

#### Request

```
curl --location --request POST 'http://127.0.0.1:8000/api/v1/archives/' \
--header 'Authorization: Token <token>' \
--form 'data_owner=<data_owner>' \
--form 'file=<archive_file_path>'
```

#### Response

```
{
    "id": "a5c2efe3-420e-4ae7-a785-54cbcfe4a0b2",
    "file": "<link>",
    "file_name": "facebook-alice.zip",
    "file_size": 88771633,
    "uploaded_at": "2020-02-12T02:25:58.311172Z",
    "data_owner": "alice"
}
```

### Trigger data parsing

For each data owner, only one archive is allowed to be parsed at a time for now.

#### Request

```
curl --location --request POST 'http://127.0.0.1:8000/api/v1/tasks/extraction' \
--header 'Authorization: Token <token>' \
--header 'Content-Type: application/json' \
--data-raw '{"archive": "XYZ", "data_owner": "alice"}'
```

#### Response
```
{
    "id": "9c18d2e8-c59c-41d1-9b80-0e8a0f04a51a",
    "data_owner": "alice",
    "archive": "a5c2efe3-420e-4ae7-a785-54cbcfe4a0b2",
    "status": "PENDING"
}
```

#### Request

```
curl --location --request POST 'http://127.0.0.1:8000/api/v1/tasks/<task_id>' \
--header 'Authorization: Token <token>' 
```

#### Response
```
{
    "staus": "RUNNING"
}
```

**Comment by lemonlatte** [comment]
The task query api endpoint needs to be 
`curl --location 'http://127.0.0.1:8000/api/v1/tasks/<task_id>' --header 'Authorization: Token <token>' `

This is limited by the django rest framework.
